language: c
compiler: gcc
jobs:
  include:
    - stage: Test
      script: Lab1/buildTest.sh
      script: Lab2/buildTest.sh
      script: Lab3/buildTest.sh
      script: Lab4/buildTest.sh
      script: Lab5/buildTest.sh
